### PR TITLE
Improved README.md which solves issue #3

### PR DESCRIPTION
**Pull request by AmulyaJain2004**
Solves issue #3 . Kindly review the changes made and suggest any change if required. Please merge my PR.

### CODE REVIEW

**Comment by anshikasrivastava17** [comment]
Hi @AmulyaJain2004 , everything else looks perfect, just remove the portion under license section and reset it to blank as it was.

**Comment by AmulyaJain2004** [comment]
Okay

**Comment by AmulyaJain2004** [comment]
@anshikasrivastava17 kindly review it. I have made the changes which you said. :)

**Comment by anshikasrivastava17** [comment]
Good work @AmulyaJain2004 !

**Pull request merged**
